[package]
edition = "2024"
name    = "gamescope-led-sync"
version = "0.0.0"

[dependencies]
clap     = { default-features = false, features = ["derive", "error-context", "help", "std", "suggestions", "usage"], version = "4" }
libc     = "0.2"
pipewire = "0.8"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true
panic            = "abort"
rpath            = false
